### ISSUE TITLE
Can't be used in the browser

### ISSUE THREAD

**Issue by seaneagan** [dart-lang/glob#1]
The glob listing functionality depends on `dart:io`, so `package:glob/glob.dart` can't be used in the browser.  This could be resolved either by moving the listing functionality to a separate library within the package, or by using a file system abstraction like [files](https://github.com/google/files.dart).

**Comment by nex3** [comment]
With [progress being made](https://github.com/lrhn/dep-configured-imports) on cross-platform code, I'm loath to remove functionality or usability to get browser support in the meantime.

**Comment by seaneagan** [comment]
Good to know, thanks!

I assume even once there is cross-platform code that dart:io will still not be available in the browser.  So some higher level file system abstraction like `files` will need to be used.  It still might be nice to have the listing functionality in a separate library so people who don't care about listing don't have to include that file system abstraction dependency in their apps.

**Comment by seaneagan** [comment]
Maybe it will still get tree shaken if `list` is not called, not sure.

**Comment by nex3** [comment]
I'm generally not too worried about adding dependencies, since pub and dart2js work together to make unused ones very light-weight. I'm not sure it's worth supporting `Glob.list` in the browser at all, though; the browser filesystem is generally quite invisible to the end user, which limits the utility of user-supplied globs. I'm also pretty uncomfortable bringing in a transitive dependency on `quiver`; since it has so many distinct pieces of functionality, it introduces a high risk of version lock.

**Comment by donny-dont** [comment]
Any chance this can be revisited? I want to use the glob stuff for testing branch names for a CI wall and the io dependency is stopping that.

**Comment by donny-dont** [comment]
@nex3 would you take a patch for this?

**Comment by nex3** [comment]
There's not really anything to revisit here. The issue here isn't implementation time, it's that the language fundamentally doesn't have a way of making this package browser-compatible while still supporting `Glob.list`. There's still progress being made on that front, but I still don't want to degrade the functionality before then.

**Comment by donny-dont** [comment]
Fair enough. Looks like configuration specific imports is 1.14.

**Comment by scheglov** [comment]
I also would like to avoid any `dart:io` dependencies.
Our packages `analyzer` and `analysis_server` don't use `dart:io`directly and in theory could be used with some virtual file systems. And this VFS has its own way of listing files. Basically `Glob` attempts to mix two concepts - FS access and matching into entity. Seems like a design smell.

**Comment by matanlurey** [comment]
@nex3: With the "hack" introduced to allow `dart:io` in the browser, can this be closed?

**Comment by nex3** [comment]
Yes, I believe so.
