### ISSUE TITLE
Publish 1.2.0

### ISSUE THREAD

**Issue by srawlins** [dart-lang/glob#26]
glob 1.2.0 needs publishing, for @nex3 . I do not have publish permissions.

**Comment by srawlins** [comment]
CC @kevmoo @munificent

**Comment by kevmoo** [comment]
We should keep in mind, this adds a handful of downstream dependencies to
everyone using glob.

**Comment by nex3** [comment]
@jakemac53 can we publish this now?

**Comment by jakemac53** [comment]
> @jakemac53 can we publish this now?

As far as I know yes, but I am not an owner on this package.

The extra dependencies are somewhat unfortunate - and fixing that will eventually require a breaking change which is unfortunate but unavoidable. I think we likely want to do that anyways though in order to move the existing file apis to extension methods, this doesn't ultimately make the situation any worse.

**Comment by nex3** [comment]
Okay, I've published.
