### ISSUE TITLE
No such file or directory.

### ISSUE THREAD

**Issue by thoward27** [dart-lang/glob#34]
I am trying to glob a bunch of images under a folder:

```
final avatars = new Glob('assets/images/avatars/**.png');
```

Unfortunately, I get: 

```
Directory listing failed, path = './assets/images/avatars/' (OS Error: No such file or directory, errno = 2)
```

Same error with the following:

```
Glob('lib/**.png')
```

I cannot seem to figure out what is actually glob-able, any direction here?

**Comment by natebosch** [comment]
If `./assets/images/avatars/` was an existing directory this would  work.

I guess the question is whether we should return an empty list for a non-existent directory rather than surface the exception? I'm inclined to say that the exception is the right behavior. If you attempt to use a glob on the shell (in `bash` and `zsh`) to a directory that does not exist it will also exit as a failure instead of giving an empty list. I'm going to close for now as working as intended.

**Comment by thoward27** [comment]
It seems a bit confusing as `Image.asset(url)` works just fine, I think glob should have access to the same files as the rest of the application

**Comment by natebosch** [comment]
You might want to follow up on the flutter repo. It sounds like this might be confusion about the working directory or what file paths are accessible when running in the app. You'll find that `Directory('assets/images/avatars').listSync()` would also throw. It has something to do with your environment, not with globbing.
